/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import io.grpc.Server;
import io.grpc.ServerBuilder;
import service.ItemServiceImpl;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Server server = ServerBuilder.forPort(8090)
        .addService(new ItemServiceImpl())
        .build();
        try {
            System.out.println("Server running on port 8090");
            server.start();
            server.awaitTermination();
        } catch (Exception e) {
            System.err.println("Failed to start the GRPC server");
        }
    }
}
